### ISSUE TITLE
作者您好，这部分代码是否有未公开部分？

### ISSUE THREAD

**Issue by Randyer-w** [hanna-xu/utils#1]
我在运行时出现img1_y未被声明。
![image](https://user-images.githubusercontent.com/40713736/92842392-16f78700-f416-11ea-8c1d-eb64cf77bb94.png)

**Comment by hanna-xu** [comment]
您好，这个是您自己的数据，是一张图片的y通道，或者根据您的需求，是其他类型的数据也可以的，不是固定的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hanna-xu/utils"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 上午10:04
收件人:&nbsp;"hanna-xu/utils"<utils@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hanna-xu/utils] 作者您好，这部分代码是否有未公开部分？ (#1)





 
我在运行时出现img1_y未被声明。

**Comment by Randyer-w** [comment]
好的 感激不尽
